### ISSUE TITLE
Hacer README.md file

### ISSUE THREAD

**Issue by crisjumbo** [drosander/signup-form#1]
Este archivo de "markdown" nos sirve como documentacion presentacional del proyecto. Es decir: 
- Nombre del Proyecto
- Descripcion
- Tecnologias que se usan
- Pasos a seguir para descargar el proyecto
- Como colaborar
- Colaboradores y autores

**Comment by bettercallandru** [comment]
Gracias por tu aporte, acabo de crear el README.md

**Comment by bettercallandru** [comment]
Confírmame por favor si el README.md está bien

**Comment by crisjumbo** [comment]
Esta muy bueno y completo para ser tu primer readme. Mañana te reviso la estructura y si quieres te hago PR. Mientras puedes ver mis repositorios para que veas más o menos cómo hago los README... Saludos desde el móvil hahaha

**Comment by crisjumbo** [comment]
Te envío un audio por Telegram, ahora voy a dormir que vivo en España xD
